[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyraid"
requires-python = ">=3.9"
dynamic = ["version"]
dependencies = []

[tool.setuptools.dynamic]
version = {attr = "pyraid.__version__"}